# Generated by Django 2.1.7 on 2019-10-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Kanishk', max_length=30),
            preserve_default=False,
        ),
    ]
