# Generated by Django 2.1.7 on 2019-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20191013_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='Users.Product'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
